target("test_umidevice")
    add_rules("host.test")
    add_tests("default")
    set_default(true)
    set_kind("binary")
    add_files("test_*.cc")
    add_deps("umidevice", "umimmio")
    umidevice_add_umitest_dep()
    add_cxxflags("-fno-exceptions", "-fno-rtti", {force = true})
target_end()
