/**
 * UMI-OS Synth - UMIM Backend AudioWorklet Processor
 *
 * Lightweight DSP-only synthesizer. Uses the same synth code as UMI-OS backend
 * but without the kernel simulation layer.
 *
 * Built from: examples/headless_webhost/src/umim_synth.cc
 * WASM binary is embedded as base64.
 *
 * WASM imports required (WASI stubs):
 *   wasi_snapshot_preview1.args_sizes_get
 *   wasi_snapshot_preview1.args_get
 *   wasi_snapshot_preview1.proc_exit
 *   env.__main_argc_argv
 *
 * WASM exports:
 *   memory, umi_create, umi_destroy, umi_process, umi_note_on, umi_note_off, etc.
 *
 * Initialization: Do NOT call _start - it causes unreachable trap.
 * Instead, call __wasm_call_ctors (if available) then umi_create.
 */

// Embedded WASM binary (base64) - built from umim_synth.cc
// To rebuild: xmake build umim_synth && base64 -i build/umim_synth.wasm
const WASM_BASE64 = "AGFzbQEAAAABSw5gAAF/YAF/AX9gAABgAX8AYAJ/fwF/YAJ/fwBgAX8BfWAEf39/fwBgA39/fwBgAXwBfWAEf39/fwF/YAJ/fQBgAX0BfWACfH8BfAKFAQQWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQ5hcmdzX3NpemVzX2dldAAEFndhc2lfc25hcHNob3RfcHJldmlldzEIYXJnc19nZXQABANlbnYQX19tYWluX2FyZ2NfYXJndgAEFndhc2lfc25hcHNob3RfcHJldmlldzEJcHJvY19leGl0AAMDKSgCAgIAAQEBBQEHCgIHBQYIBQMLBgABBgEIAAAAAAACDAkJDQEBAwMABAUBcAECAgUEAQEQEAYIAX8BQaCwBAsHwAUmBm1lbW9yeQIACnVtaV9jcmVhdGUABQt1bWlfZGVzdHJveQAGEnVtaV9nZXRfcG9ydF9jb3VudAAHEXVtaV9nZXRfcG9ydF9uYW1lAAgWdW1pX2dldF9wb3J0X2RpcmVjdGlvbgAJEXVtaV9nZXRfcG9ydF9raW5kAAoTdW1pX3NldF9wb3J0X2J1ZmZlcgALE3VtaV9nZXRfcG9ydF9idWZmZXIADA51bWlfc2VuZF9ldmVudAANDnVtaV9yZWN2X2V2ZW50AA4QdW1pX2NsZWFyX2V2ZW50cwAPC3VtaV9wcm9jZXNzABASdW1pX3Byb2Nlc3Nfc2ltcGxlABMLdW1pX25vdGVfb24AFAx1bWlfbm90ZV9vZmYAFQ11bWlfc2V0X3BhcmFtABYNdW1pX2dldF9wYXJhbQAXE3VtaV9nZXRfcGFyYW1fY291bnQAGBJ1bWlfZ2V0X3BhcmFtX25hbWUAGRF1bWlfZ2V0X3BhcmFtX21pbgAXEXVtaV9nZXRfcGFyYW1fbWF4ABoVdW1pX2dldF9wYXJhbV9kZWZhdWx0ABcTdW1pX2dldF9wYXJhbV9jdXJ2ZQAbEHVtaV9nZXRfcGFyYW1faWQAGxJ1bWlfZ2V0X3BhcmFtX3VuaXQAGQ51bWlfcHJvY2Vzc19jYwAcFnVtaV9nZXRfcHJvY2Vzc29yX25hbWUAHQx1bWlfZ2V0X25hbWUAHg51bWlfZ2V0X3ZlbmRvcgAfD3VtaV9nZXRfdmVyc2lvbgAgDHVtaV9nZXRfdHlwZQAhGV9faW5kaXJlY3RfZnVuY3Rpb25fdGFibGUBAAZfc3RhcnQAIgZtYWxsb2MAKARmcmVlACkZX2Vtc2NyaXB0ZW5fc3RhY2tfcmVzdG9yZQAqHGVtc2NyaXB0ZW5fc3RhY2tfZ2V0X2N1cnJlbnQAKwkHAQBBAQsBBAwBDQrzYCgDAAELEgBBlCRBADYCAEGQJEEAOgAACxIAQZQkQQA2AgBBmCRBADYCAAsEAEECCyEBAX9BvAghASAAQQFNBH8gAEEDdEHACGooAgAFQbwICwsbAQF/IABBAU0EfyAAQQN0QcQIai0AAAVBAAsLGwEBfyAAQQFNBH8gAEEDdEHFCGotAAAFQQALCxIAIABBAUYEQEGYJCABNgIACwsQAEGYJCgCAEEAIABBAUYbC1sAAkAgAA0AQZQkKAIAIgBBP0sNAEGUJCAAQQFqNgIAIABBBHQhAEEIIAIgAkEITxsiAgRAIABBoCRqIAEgAvwKAAALIABBrCRqIAM2AgAgAEGoJGogAjoAAAsLBABBAAsKAEGUJEEANgIAC80aAwN8BH0TfyMAQRBrIhEkACABBEAgA7MhBwJAQZAkLQAABEBBwCEqAgAgB1sNAQtB5CMgBzgCAEHAISAHOAIAQdAjIAc4AgBBiCMgBzgCAEHAIiAHOAIAQfghIAc4AgBB1CNDAACAPyAHlSIIOAIAQYwjIAg4AgBBxCIgCDgCAEH8ISAIOAIAQcAjQfAjKgIAIgg4AgBB+CIgCDgCAEGwIiAIOAIAQeghIAg4AgBBzCNB9CMqAgAiCEMAAHpElUMAAKBAlUNvEoM6IAhDAAAAAF4bIgg4AgBByCNB7CMqAgAiCUMAAHpElUMAAKBAlUNvEoM6IAlDAAAAAF4bIgk4AgBBxCNB6CMqAgAiCkMAAHpElUMAAKBAlUNvEoM6IApDAAAAAF4bIgo4AgBBhCMgCDgCAEGAIyAJOAIAQfwiIAo4AgBBvCIgCDgCAEG4IiAJOAIAQbQiIAo4AgBB9CEgCDgCAEHwISAJOAIAQewhIAo4AgBBkCRBAToAAEHMIUPNzMw9QwAAgD9B/CMqAgBDAAAYQZRDAAAAP5KVIgggCEPNzMw9XRsiCDgCAEGUIiAIOAIAQdwiIAg4AgBBpCMgCDgCAEMXt9E4Q83MzD5B+CMqAgAgB5UiByAHQ83MzD5eGyIHIAdDF7fROF0bQ9sPSUCUIQcjAEEQayIQJAACQCAHvCIDQf////8HcSIAQdqfpPoDTQRAIABBgICAzANJDQEgB7sQJCEHDAELIABB0aftgwRNBEAgB7shBCAAQeOX24AETQRAIANBAEgEQCAERBgtRFT7Ifk/oBAljCEHDAMLIAREGC1EVPsh+b+gECUhBwwCC0QYLURU+yEJwEQYLURU+yEJQCADQQBOGyAEoJoQJCEHDAELIABB1eOIhwRNBEAgAEHf27+FBE0EQCAHuyEEIANBAEgEQCAERNIhM3982RJAoBAlIQcMAwsgBETSITN/fNkSwKAQJYwhBwwCC0QYLURU+yEZQEQYLURU+yEZwCADQQBIGyAHu6AQJCEHDAELIABBgICA/AdPBEAgByAHkyEHDAELIwBBEGsiEiQAAkAgB7wiGUH/////B3EiAEHan6TuBE0EQCAQIAe7IgUgBUSDyMltMF/kP6JEAAAAAAAAOEOgRAAAAAAAADjDoCIERAAAAFD7Ifm/oqAgBERjYhphtBBRvqKgIgY5AwggBPwCIQAgBkQAAABg+yHpv2MEQCAQIAUgBEQAAAAAAADwv6AiBEQAAABQ+yH5v6KgIAREY2IaYbQQUb6ioDkDCCAAQQFrIQAMAgsgBkQAAABg+yHpP2RFDQEgECAFIAREAAAAAAAA8D+gIgREAAAAUPsh+b+ioCAERGNiGmG0EFG+oqA5AwggAEEBaiEADAELIABBgICA/AdPBEAgECAHIAeTuzkDCEEAIQAMAQsgEiAAIABBF3ZBlgFrIgBBF3Rrvrs5AwggEkEIaiEXIwBBsARrIgwkACAAIABBA2tBGG0iA0EAIANBAEobIhZBaGxqIQ9BoAsoAgAiDUEATgRAIA1BAWohACAWIQMDQCAMQcACaiALQQN0aiADQQBIBHxEAAAAAAAAAAAFIANBAnRBsAtqKAIAtws5AwAgA0EBaiEDIAtBAWoiCyAARw0ACwsgD0EYayEOQQAhACANQQAgDUEAShshCwNAQQAhA0QAAAAAAAAAACEEA0AgFyADQQN0aisDACAMQcACaiAAIANrQQN0aisDAKIgBKAhBCADQQFqIgNBAUcNAAsgDCAAQQN0aiAEOQMAIAAgC0YhAyAAQQFqIQAgA0UNAAtBLyAPayEaQTAgD2shGCAPQRlrIRsgDSEAAkADQCAMIABBA3RqKwMAIQRBACEDIAAhCyAAQQBKBEADQCAMQeADaiADQQJ0aiAERAAAAAAAAHA+ovwCtyIFRAAAAAAAAHDBoiAEoPwCNgIAIAwgC0EBayILQQN0aisDACAFoCEEIANBAWoiAyAARw0ACwsgBCAOECYiBCAERAAAAAAAAMA/opxEAAAAAAAAIMCioCIEIAT8AiITt6EhBAJAAkACQAJ/IA5BAEwiHEUEQCAAQQJ0IAxqIgMgAygC3AMiAyADIBh1IgMgGHRrIgs2AtwDIAMgE2ohEyALIBp1DAELIA4NASAAQQJ0IAxqKALcA0EXdQsiFEEATA0CDAELQQIhFCAERAAAAAAAAOA/Zg0AQQAhFAwBC0EAIQNBACEVQQEhCyAAQQBKBEADQCAMQeADaiADQQJ0aiIdKAIAIQsCfwJAIB0gFQR/Qf///wcFIAtFDQFBgICACAsgC2s2AgBBASEVQQAMAQtBACEVQQELIQsgA0EBaiIDIABHDQALCwJAIBwNAEH///8DIQMCQAJAIBsOAgEAAgtB////ASEDCyAAQQJ0IAxqIhUgFSgC3AMgA3E2AtwDCyATQQFqIRMgFEECRw0ARAAAAAAAAPA/IAShIQRBAiEUIAsNACAERAAAAAAAAPA/IA4QJqEhBAsgBEQAAAAAAAAAAGEEQEEAIQsCQCANIAAiA04NAANAIAxB4ANqIANBAWsiA0ECdGooAgAgC3IhCyADIA1KDQALIAtFDQADQCAOQRhrIQ4gDEHgA2ogAEEBayIAQQJ0aigCAEUNAAsMAwtBASEDA0AgAyILQQFqIQMgDEHgA2ogDSALa0ECdGooAgBFDQALIAAgC2ohCwNAIAxBwAJqIABBAWoiAEEDdGogACAWakECdEGwC2ooAgC3OQMAQQAhA0QAAAAAAAAAACEEA0AgFyADQQN0aisDACAMQcACaiAAIANrQQN0aisDAKIgBKAhBCADQQFqIgNBAUcNAAsgDCAAQQN0aiAEOQMAIAAgC0gNAAsgCyEADAELCwJAIARBGCAPaxAmIgREAAAAAAAAcEFmBEAgDEHgA2ogAEECdGogBEQAAAAAAABwPqL8AiIDt0QAAAAAAABwwaIgBKD8AjYCACAAQQFqIQAgDyEODAELIAT8AiEDCyAMQeADaiAAQQJ0aiADNgIAC0QAAAAAAADwPyAOECYhBCAAQQBOBEAgACEDA0AgDCADIgtBA3RqIAQgDEHgA2ogA0ECdGooAgC3ojkDACADQQFrIQMgBEQAAAAAAABwPqIhBCALDQALIAAhCwNARAAAAAAAAAAAIQRBACEDIA0gACALayIOIA0gDkgbIg9BAE4EQANAIANBA3RBgCFqKwMAIAwgAyALakEDdGorAwCiIASgIQQgAyAPRyEWIANBAWohAyAWDQALCyAMQaABaiAOQQN0aiAEOQMAIAtBAEohAyALQQFrIQsgAw0ACwtEAAAAAAAAAAAhBCAAQQBOBEADQCAAIgNBAWshACAEIAxBoAFqIANBA3RqKwMAoCEEIAMNAAsLIBIgBJogBCAUGzkDACAMQbAEaiQAIBNBB3EhACASKwMAIQQgGUEASARAIBAgBJo5AwhBACAAayEADAELIBAgBDkDCAsgEkEQaiQAIBArAwghBAJAAkACQAJAIABBA3FBAWsOAwECAwALIAQQJCEHDAMLIAQQJSEHDAILIASaECQhBwwBCyAEECWMIQcLIBBBEGokAEHIIUMAAMA/IAcgB5IiByAHQwAAwD9eGyIHOAIAQZAiIAc4AgBB2CIgBzgCAEGgIyAHOAIAC0EAIQBBmCQgATYCAEGUJCgCACILBEADQCALIAAiAUEBaiIASwRAIAFBBHRBoCRqIQMgACEBA0AgAUEEdCINQawkaigCACADKAIMSQRAIBEgAykCCDcDCCARIAMpAgA3AwAgAyANQaAkaiINKQMINwMIIAMgDSkDADcDACANIBEpAwg3AgggDSARKQMANwIACyABQQFqIgEgC0cNAAsLIAAgC0cNAAsLIAIEQEEAIQNBACEBA0ACQCABQZQkKAIAIgtPDQADQCABQQR0IgBBrCRqKAIAIANLDQECQCAAQaAkaiIALQAIIg1BAkkNAAJAAkAgACwAACIOQXBxIg9BkH9GIA1BAkdxRQRAIA5BkH9IDQEgD0GQf0cNAyAALQACDQMMAQsgAC0AAiINDQELIAAtAAEhAAJAQYkiLQAAQQFHDQBBiCItAAAgAEcNAEHgIS0AAEUNAEHgIUEEOgAACwJAQdEiLQAAQQFHDQBB0CItAAAgAEcNAEGoIi0AAEUNAEGoIkEEOgAACwJAQZkjLQAAQQFHDQBBmCMtAAAgAEcNAEHwIi0AAEUNAEHwIkEEOgAAC0HhIy0AAEEBRw0BQeAjLQAAIABHDQFBuCMtAABFDQFBuCNBBDoAAAwBCyAALQABIA0QEUGUJCgCACELCyABQQFqIgEgC0kNAAsLAn1DAACAP0HEIRASQwAAAACSQYwiEBKSQdQiEBKSQZwjEBKSQYAkKgIAlEMAAIA+lCIHQwAAgD9eDQAaQwAAgL8gB0MAAIC/XQ0AGiAHIAdDAAAAv5QgB5RDAADAP5KUCyEHQZgkKAIAIANBAnRqIAc4AgAgA0EBaiIDIAJHDQALC0GUJEEANgIACyARQRBqJAAL6gMCBH8BfUHEISECAkBBiSItAAAiBEEBRgRAQYgiLQAAIABGDQELAkBB0SItAAAiA0EBRw0AQdAiLQAAIABHDQBBjCIhAgwBCwJAQZkjLQAAIgVBAUcNAEGYIy0AACAARw0AQdQiIQIMAQsCQEHhIy0AACICQQFHDQBB4CMtAAAgAEcNAEGcIyECDAELAkAgAyAEcSIDRQ0AIAIgBXFFDQBBiCIgADoAAEHQIUIANwIAQcQhQQA2AgBBiSJBAToAAEHgIUEBOgAAQdghQgA3AgBBhCIgAbNDAAD+QpU4AgBBgCIgALNDAACKwpJDAABAQZUQI0MAANxDlEH4ISoCAJU4AgAPC0GcI0HUIiAFG0GMIkHEISAEGyADGyICIAGzQwAA/kKVOAJAIAIgADoARCACKgI0IQYgAiAAs0MAAIrCkkMAAEBBlRAjQwAA3EOUIAaVOAI8QdgBQZABIAUbQcgAQQAgBBsgAxtBxCFqQQA2AgAgAkIANwIUIAJCADcCDCACQQE6AEUgAkEBOgAcDwsgAiAAOgBEIAJCADcCDCACQQA2AgAgAkEBOgBFIAJBAToAHCACQgA3AhQgAiABs0MAAP5ClTgCQCACIACzQwAAisKSQwAAQEGVECNDAADcQ5QgAioCNJU4AjwLwQQBBH0gAC0ARUEBRgR9An0gACoCACICIAAqAjwiA10EQCACIAOVIgEgAZIgASABlJNDAACAv5IMAQtDAAAAACACQwAAgD8gA5NeRQ0AGiACQwAAgL+SIAOVIgEgASABIAGUkpJDAACAP5ILIQEgACADIAKSIgMgA/wAspMiA0MAAIA/kiADIANDAAAAAF0bOAIAIAAgAiACkkMAAIC/kiABkyICIAAqAgRDAAAAP5QiASABIAIgACoCDCIDkyAAKgIIIgQgACoCECIClJOUIAKSIgKUIAOSIgOTIAQgApSTIgQ4AhQgACABIASUIAKSIgI4AhAgACABIAKUIAOSIgM4AgwgACAEIAOSOAIYIAAqAjghAQJAAkACQAJAAkACQAJAAkAgAC0AHA4FBwABBQIDCyAAIAEgACoCKJVDAACAPyAAKgIgIgGTlCABkiICOAIgIAJDd75/P2BFDQUgAEECOgAcIABBgICA/AM2AiBDAACAPyEBDAMLIAAgASAAKgIslSAAKgIkIgEgACoCICICk5QgApIiAjgCICACIAFDbxKDOpJfRQ0EIABBAzoAHCAAIAE4AiAMAgsgACABIAAqAjCVQwAAAAAgACoCICIBk5QgAZIiAjgCICACQ28SgzpfRQ0DIABBADoAHAwECyAAKgIgIQELIAMgAZQgACoCQJQPCyAAIAAqAiQiAjgCIAsgAyAClCAAKgJAlA8LIABBADYCICAAQQA6AEUgA0MAAAAAlCAAKgJAlAVDAAAAAAsLDgAgAiABIAJBgPcCEBALCAAgACABEBELqgEAAkBBiSItAABBAUcNAEGIIi0AACAARw0AQeAhLQAARQ0AQeAhQQQ6AAALAkBB0SItAABBAUcNAEHQIi0AACAARw0AQagiLQAARQ0AQagiQQQ6AAALAkBBmSMtAABBAUcNAEGYIy0AACAARw0AQfAiLQAARQ0AQfAiQQQ6AAALAkBB4SMtAABBAUcNAEHgIy0AACAARw0AQbgjLQAARQ0AQbgjQQQ6AAALCwMAAQsHAEMAAAAACwQAQQALBQBBvAgLBwBDAACAPwsEAEEACwMAAQsFAEGKCAsFAEGmCAsFAEGwCAsFAEG3CAsEAEEBC40BAQR/An8jAEEQayIAJAACQCAAQQxqIABBCGoQAEUEQCAAKAIMIgIEfyAAIAJBAnQiAkETakFwcWsiASQAIAEgACgCCEEPakFwcWsiAyQAIAEgAmpBADYCACABIAMQAQ0CIAAoAgwFQQALIAEQAiEBIABBEGokACABDAILQccAEAMAC0HHABADAAsQAwAL5wEDAnwBfwF+An0CQCAAvEEUdkH/D3EiA0GwCEkNAEMAAAAAIABDAACA/1sNARogA0H4D08EQCAAIACSDwsgAEMAAAAAXgRAIwBBEGsiA0MAAABwOAIMIAMqAgxDAAAAcJQPCyAAQwAAFsNfRQ0AIwBBEGsiA0MAAAAQOAIMIAMqAgxDAAAAEJQPC0HYCisDACAAuyIBIAFB0AorAwAiAaAiAiABoaEiAaJB4AorAwCgIAEgAaKiQegKKwMAIAGiRAAAAAAAAPA/oKAgAr0iBEIvhiAEp0EfcUEDdEHQCGopAwB8v6K2CwtLAQJ8IAAgACAAoiIBoiICIAEgAaKiIAFEp0Y7jIfNxj6iRHTnyuL5ACq/oKIgAiABRLL7bokQEYE/okR3rMtUVVXFv6CiIACgoLYLTwEBfCAAIACiIgAgACAAoiIBoiAARGlQ7uBCk/k+okQnHg/oh8BWv6CiIAFEQjoF4VNVpT+iIABEgV4M/f//37+iRAAAAAAAAPA/oKCgtguoAQACQCABQYAITgRAIABEAAAAAAAA4H+iIQAgAUH/D0kEQCABQf8HayEBDAILIABEAAAAAAAA4H+iIQBB/RcgASABQf0XTxtB/g9rIQEMAQsgAUGBeEoNACAARAAAAAAAAGADoiEAIAFBuHBLBEAgAUHJB2ohAQwBCyAARAAAAAAAAGADoiEAQfBoIAEgAUHwaE0bQZIPaiEBCyAAIAFB/wdqrUI0hr+iC0kBAn9BhCQoAgAiASAAQQdqQXhxIgJqIQACQCACQQAgACABTRtFBEAgAD8AQRB0TQ0BC0GgLEEwNgIAQX8PC0GEJCAANgIAIAEL3icBC38jAEEQayIKJAACQAJAAkACQAJAAkACQAJAAkACQCAAQfQBTQRAQaQsKAIAIgRBECAAQQtqQfgDcSAAQQtJGyIGQQN2IgB2IgFBA3EEQAJAIAFBf3NBAXEgAGoiAkEDdCIBQcwsaiIAIAFB1CxqKAIAIgEoAggiBUYEQEGkLCAEQX4gAndxNgIADAELIAUgADYCDCAAIAU2AggLIAFBCGohACABIAJBA3QiAkEDcjYCBCABIAJqIgEgASgCBEEBcjYCBAwLCyAGQawsKAIAIghNDQEgAQRAAkBBAiAAdCICQQAgAmtyIAEgAHRxaCIBQQN0IgBBzCxqIgIgAEHULGooAgAiACgCCCIFRgRAQaQsIARBfiABd3EiBDYCAAwBCyAFIAI2AgwgAiAFNgIICyAAIAZBA3I2AgQgACAGaiIHIAFBA3QiASAGayIFQQFyNgIEIAAgAWogBTYCACAIBEAgCEF4cUHMLGohAUG4LCgCACECAn8gBEEBIAhBA3Z0IgNxRQRAQaQsIAMgBHI2AgAgAQwBCyABKAIICyEDIAEgAjYCCCADIAI2AgwgAiABNgIMIAIgAzYCCAsgAEEIaiEAQbgsIAc2AgBBrCwgBTYCAAwLC0GoLCgCACILRQ0BIAtoQQJ0QdQuaigCACICKAIEQXhxIAZrIQMgAiEBA0ACQCABKAIQIgBFBEAgASgCFCIARQ0BCyAAKAIEQXhxIAZrIgEgAyABIANJIgEbIQMgACACIAEbIQIgACEBDAELCyACKAIYIQkgAiACKAIMIgBHBEAgAigCCCIBIAA2AgwgACABNgIIDAoLIAIoAhQiAQR/IAJBFGoFIAIoAhAiAUUNAyACQRBqCyEFA0AgBSEHIAEiAEEUaiEFIAAoAhQiAQ0AIABBEGohBSAAKAIQIgENAAsgB0EANgIADAkLQX8hBiAAQb9/Sw0AIABBC2oiAUF4cSEGQagsKAIAIgdFDQBBHyEIQQAgBmshAyAAQfT//wdNBEAgBkEmIAFBCHZnIgBrdkEBcSAAQQF0a0E+aiEICwJAAkACQCAIQQJ0QdQuaigCACIBRQRAQQAhAAwBC0EAIQAgBkEZIAhBAXZrQQAgCEEfRxt0IQIDQAJAIAEoAgRBeHEgBmsiBCADTw0AIAEhBSAEIgMNAEEAIQMgASEADAMLIAAgASgCFCIEIAQgASACQR12QQRxaigCECIBRhsgACAEGyEAIAJBAXQhAiABDQALCyAAIAVyRQRAQQAhBUECIAh0IgBBACAAa3IgB3EiAEUNAyAAaEECdEHULmooAgAhAAsgAEUNAQsDQCAAKAIEQXhxIAZrIgIgA0khASACIAMgARshAyAAIAUgARshBSAAKAIQIgEEfyABBSAAKAIUCyIADQALCyAFRQ0AIANBrCwoAgAgBmtPDQAgBSgCGCEIIAUgBSgCDCIARwRAIAUoAggiASAANgIMIAAgATYCCAwICyAFKAIUIgEEfyAFQRRqBSAFKAIQIgFFDQMgBUEQagshAgNAIAIhBCABIgBBFGohAiAAKAIUIgENACAAQRBqIQIgACgCECIBDQALIARBADYCAAwHCyAGQawsKAIAIgVNBEBBuCwoAgAhAAJAIAUgBmsiAUEQTwRAIAAgBmoiAiABQQFyNgIEIAAgBWogATYCACAAIAZBA3I2AgQMAQsgACAFQQNyNgIEIAAgBWoiASABKAIEQQFyNgIEQQAhAkEAIQELQawsIAE2AgBBuCwgAjYCACAAQQhqIQAMCQsgBkGwLCgCACICSQRAQbAsIAIgBmsiATYCAEG8LEG8LCgCACIAIAZqIgI2AgAgAiABQQFyNgIEIAAgBkEDcjYCBCAAQQhqIQAMCQtBACEAIAZBL2oiAwJ/QfwvKAIABEBBhDAoAgAMAQtBiDBCfzcCAEGAMEKAoICAgIAENwIAQfwvIApBDGpBcHFB2KrVqgVzNgIAQZAwQQA2AgBB4C9BADYCAEGAIAsiAWoiBEEAIAFrIgdxIgEgBk0NCEHcLygCACIFBEBB1C8oAgAiCCABaiIJIAhNDQkgBSAJSQ0JCwJAQeAvLQAAQQRxRQRAAkACQAJAAkBBvCwoAgAiBQRAQeQvIQADQCAAKAIAIgggBU0EQCAFIAggACgCBGpJDQMLIAAoAggiAA0ACwtBABAnIgJBf0YNAyABIQRBgDAoAgAiAEEBayIFIAJxBEAgASACayACIAVqQQAgAGtxaiEECyAEIAZNDQNB3C8oAgAiAARAQdQvKAIAIgUgBGoiByAFTQ0EIAAgB0kNBAsgBBAnIgAgAkcNAQwFCyAEIAJrIAdxIgQQJyICIAAoAgAgACgCBGpGDQEgAiEACyAAQX9GDQEgBkEwaiAETQRAIAAhAgwEC0GEMCgCACICIAMgBGtqQQAgAmtxIgIQJ0F/Rg0BIAIgBGohBCAAIQIMAwsgAkF/Rw0CC0HgL0HgLygCAEEEcjYCAAsgARAnIQJBABAnIQAgAkF/Rg0FIABBf0YNBSAAIAJNDQUgACACayIEIAZBKGpNDQULQdQvQdQvKAIAIARqIgA2AgBB2C8oAgAgAEkEQEHYLyAANgIACwJAQbwsKAIAIgMEQEHkLyEAA0AgAiAAKAIAIgEgACgCBCIFakYNAiAAKAIIIgANAAsMBAtBtCwoAgAiAEEAIAAgAk0bRQRAQbQsIAI2AgALQQAhAEHoLyAENgIAQeQvIAI2AgBBxCxBfzYCAEHILEH8LygCADYCAEHwL0EANgIAA0AgAEEDdCIBQdQsaiABQcwsaiIFNgIAIAFB2CxqIAU2AgAgAEEBaiIAQSBHDQALQbAsIARBKGsiAEF4IAJrQQdxIgFrIgU2AgBBvCwgASACaiIBNgIAIAEgBUEBcjYCBCAAIAJqQSg2AgRBwCxBjDAoAgA2AgAMBAsgAiADTQ0CIAEgA0sNAiAAKAIMQQhxDQIgACAEIAVqNgIEQbwsIANBeCADa0EHcSIAaiIBNgIAQbAsQbAsKAIAIARqIgIgAGsiADYCACABIABBAXI2AgQgAiADakEoNgIEQcAsQYwwKAIANgIADAMLQQAhAAwGC0EAIQAMBAtBtCwoAgAgAksEQEG0LCACNgIACyACIARqIQVB5C8hAAJAA0AgBSAAKAIAIgFHBEAgACgCCCIADQEMAgsLIAAtAAxBCHFFDQMLQeQvIQADQAJAIAAoAgAiASADTQRAIAMgASAAKAIEaiIFSQ0BCyAAKAIIIQAMAQsLQbAsIARBKGsiAEF4IAJrQQdxIgFrIgc2AgBBvCwgASACaiIBNgIAIAEgB0EBcjYCBCAAIAJqQSg2AgRBwCxBjDAoAgA2AgAgAyAFQScgBWtBB3FqQS9rIgAgACADQRBqSRsiAUEbNgIEIAFB7C8pAgA3AhAgAUHkLykCADcCCEHsLyABQQhqNgIAQegvIAQ2AgBB5C8gAjYCAEHwL0EANgIAIAFBGGohAANAIABBBzYCBCAAQQhqIQIgAEEEaiEAIAIgBUkNAAsgASADRg0AIAEgASgCBEF+cTYCBCADIAEgA2siAkEBcjYCBCABIAI2AgACfyACQf8BTQRAIAJBeHFBzCxqIQACf0GkLCgCACIBQQEgAkEDdnQiAnFFBEBBpCwgASACcjYCACAADAELIAAoAggLIQEgACADNgIIIAEgAzYCDEEMIQJBCAwBC0EfIQAgAkH///8HTQRAIAJBJiACQQh2ZyIAa3ZBAXEgAEEBdGtBPmohAAsgAyAANgIcIANCADcCECAAQQJ0QdQuaiEBAkACQEGoLCgCACIFQQEgAHQiBHFFBEBBqCwgBCAFcjYCACABIAM2AgAMAQsgAkEZIABBAXZrQQAgAEEfRxt0IQAgASgCACEFA0AgBSIBKAIEQXhxIAJGDQIgAEEddiEFIABBAXQhACABIAVBBHFqIgQoAhAiBQ0ACyAEIAM2AhALIAMgATYCGEEIIQIgAyIBIQBBDAwBCyABKAIIIgAgAzYCDCABIAM2AgggAyAANgIIQQAhAEEYIQJBDAsgA2ogATYCACACIANqIAA2AgALQbAsKAIAIgAgBk0NAEGwLCAAIAZrIgE2AgBBvCxBvCwoAgAiACAGaiICNgIAIAIgAUEBcjYCBCAAIAZBA3I2AgQgAEEIaiEADAQLQaAsQTA2AgBBACEADAMLIAAgAjYCACAAIAAoAgQgBGo2AgQgAkF4IAJrQQdxaiIIIAZBA3I2AgQgAUF4IAFrQQdxaiIEIAYgCGoiA2shBwJAQbwsKAIAIARGBEBBvCwgAzYCAEGwLEGwLCgCACAHaiIANgIAIAMgAEEBcjYCBAwBC0G4LCgCACAERgRAQbgsIAM2AgBBrCxBrCwoAgAgB2oiADYCACADIABBAXI2AgQgACADaiAANgIADAELIAQoAgQiAEEDcUEBRgRAIABBeHEhCSAEKAIMIQICQCAAQf8BTQRAIAQoAggiASACRgRAQaQsQaQsKAIAQX4gAEEDdndxNgIADAILIAEgAjYCDCACIAE2AggMAQsgBCgCGCEGAkAgAiAERwRAIAQoAggiACACNgIMIAIgADYCCAwBCwJAIAQoAhQiAAR/IARBFGoFIAQoAhAiAEUNASAEQRBqCyEBA0AgASEFIAAiAkEUaiEBIAAoAhQiAA0AIAJBEGohASACKAIQIgANAAsgBUEANgIADAELQQAhAgsgBkUNAAJAIAQoAhwiAEECdEHULmoiASgCACAERgRAIAEgAjYCACACDQFBqCxBqCwoAgBBfiAAd3E2AgAMAgsCQCAEIAYoAhBGBEAgBiACNgIQDAELIAYgAjYCFAsgAkUNAQsgAiAGNgIYIAQoAhAiAARAIAIgADYCECAAIAI2AhgLIAQoAhQiAEUNACACIAA2AhQgACACNgIYCyAHIAlqIQcgBCAJaiIEKAIEIQALIAQgAEF+cTYCBCADIAdBAXI2AgQgAyAHaiAHNgIAIAdB/wFNBEAgB0F4cUHMLGohAAJ/QaQsKAIAIgFBASAHQQN2dCICcUUEQEGkLCABIAJyNgIAIAAMAQsgACgCCAshASAAIAM2AgggASADNgIMIAMgADYCDCADIAE2AggMAQtBHyECIAdB////B00EQCAHQSYgB0EIdmciAGt2QQFxIABBAXRrQT5qIQILIAMgAjYCHCADQgA3AhAgAkECdEHULmohAAJAAkBBqCwoAgAiAUEBIAJ0IgVxRQRAQagsIAEgBXI2AgAgACADNgIADAELIAdBGSACQQF2a0EAIAJBH0cbdCECIAAoAgAhAQNAIAEiACgCBEF4cSAHRg0CIAJBHXYhASACQQF0IQIgACABQQRxaiIFKAIQIgENAAsgBSADNgIQCyADIAA2AhggAyADNgIMIAMgAzYCCAwBCyAAKAIIIgEgAzYCDCAAIAM2AgggA0EANgIYIAMgADYCDCADIAE2AggLIAhBCGohAAwCCwJAIAhFDQACQCAFKAIcIgFBAnRB1C5qIgIoAgAgBUYEQCACIAA2AgAgAA0BQagsIAdBfiABd3EiBzYCAAwCCwJAIAUgCCgCEEYEQCAIIAA2AhAMAQsgCCAANgIUCyAARQ0BCyAAIAg2AhggBSgCECIBBEAgACABNgIQIAEgADYCGAsgBSgCFCIBRQ0AIAAgATYCFCABIAA2AhgLAkAgA0EPTQRAIAUgAyAGaiIAQQNyNgIEIAAgBWoiACAAKAIEQQFyNgIEDAELIAUgBkEDcjYCBCAFIAZqIgQgA0EBcjYCBCADIARqIAM2AgAgA0H/AU0EQCADQXhxQcwsaiEAAn9BpCwoAgAiAUEBIANBA3Z0IgJxRQRAQaQsIAEgAnI2AgAgAAwBCyAAKAIICyEBIAAgBDYCCCABIAQ2AgwgBCAANgIMIAQgATYCCAwBC0EfIQAgA0H///8HTQRAIANBJiADQQh2ZyIAa3ZBAXEgAEEBdGtBPmohAAsgBCAANgIcIARCADcCECAAQQJ0QdQuaiEBAkACQCAHQQEgAHQiAnFFBEBBqCwgAiAHcjYCACABIAQ2AgAgBCABNgIYDAELIANBGSAAQQF2a0EAIABBH0cbdCEAIAEoAgAhAQNAIAEiAigCBEF4cSADRg0CIABBHXYhASAAQQF0IQAgAiABQQRxaiIHKAIQIgENAAsgByAENgIQIAQgAjYCGAsgBCAENgIMIAQgBDYCCAwBCyACKAIIIgAgBDYCDCACIAQ2AgggBEEANgIYIAQgAjYCDCAEIAA2AggLIAVBCGohAAwBCwJAIAlFDQACQCACKAIcIgFBAnRB1C5qIgUoAgAgAkYEQCAFIAA2AgAgAA0BQagsIAtBfiABd3E2AgAMAgsCQCACIAkoAhBGBEAgCSAANgIQDAELIAkgADYCFAsgAEUNAQsgACAJNgIYIAIoAhAiAQRAIAAgATYCECABIAA2AhgLIAIoAhQiAUUNACAAIAE2AhQgASAANgIYCwJAIANBD00EQCACIAMgBmoiAEEDcjYCBCAAIAJqIgAgACgCBEEBcjYCBAwBCyACIAZBA3I2AgQgAiAGaiIFIANBAXI2AgQgAyAFaiADNgIAIAgEQCAIQXhxQcwsaiEAQbgsKAIAIQECf0EBIAhBA3Z0IgcgBHFFBEBBpCwgBCAHcjYCACAADAELIAAoAggLIQQgACABNgIIIAQgATYCDCABIAA2AgwgASAENgIIC0G4LCAFNgIAQawsIAM2AgALIAJBCGohAAsgCkEQaiQAIAAL3AsBCH8CQCAARQ0AIABBCGsiAyAAQQRrKAIAIgJBeHEiAGohBQJAIAJBAXENACACQQJxRQ0BIAMgAygCACIEayIDQbQsKAIASQ0BIAAgBGohAAJAAkACQEG4LCgCACADRwRAIAMoAgwhASAEQf8BTQRAIAEgAygCCCICRw0CQaQsQaQsKAIAQX4gBEEDdndxNgIADAULIAMoAhghByABIANHBEAgAygCCCICIAE2AgwgASACNgIIDAQLIAMoAhQiAgR/IANBFGoFIAMoAhAiAkUNAyADQRBqCyEEA0AgBCEGIAIiAUEUaiEEIAEoAhQiAg0AIAFBEGohBCABKAIQIgINAAsgBkEANgIADAMLIAUoAgQiAkEDcUEDRw0DQawsIAA2AgAgBSACQX5xNgIEIAMgAEEBcjYCBCAFIAA2AgAPCyACIAE2AgwgASACNgIIDAILQQAhAQsgB0UNAAJAIAMoAhwiBEECdEHULmoiAigCACADRgRAIAIgATYCACABDQFBqCxBqCwoAgBBfiAEd3E2AgAMAgsCQCADIAcoAhBGBEAgByABNgIQDAELIAcgATYCFAsgAUUNAQsgASAHNgIYIAMoAhAiAgRAIAEgAjYCECACIAE2AhgLIAMoAhQiAkUNACABIAI2AhQgAiABNgIYCyADIAVPDQAgBSgCBCIEQQFxRQ0AAkACQAJAAkAgBEECcUUEQEG8LCgCACAFRgRAQbwsIAM2AgBBsCxBsCwoAgAgAGoiADYCACADIABBAXI2AgQgA0G4LCgCAEcNBkGsLEEANgIAQbgsQQA2AgAPC0G4LCgCACIHIAVGBEBBuCwgAzYCAEGsLEGsLCgCACAAaiIANgIAIAMgAEEBcjYCBCAAIANqIAA2AgAPCyAEQXhxIABqIQAgBSgCDCEBIARB/wFNBEAgBSgCCCICIAFGBEBBpCxBpCwoAgBBfiAEQQN2d3E2AgAMBQsgAiABNgIMIAEgAjYCCAwECyAFKAIYIQggASAFRwRAIAUoAggiAiABNgIMIAEgAjYCCAwDCyAFKAIUIgIEfyAFQRRqBSAFKAIQIgJFDQIgBUEQagshBANAIAQhBiACIgFBFGohBCABKAIUIgINACABQRBqIQQgASgCECICDQALIAZBADYCAAwCCyAFIARBfnE2AgQgAyAAQQFyNgIEIAAgA2ogADYCAAwDC0EAIQELIAhFDQACQCAFKAIcIgRBAnRB1C5qIgIoAgAgBUYEQCACIAE2AgAgAQ0BQagsQagsKAIAQX4gBHdxNgIADAILAkAgBSAIKAIQRgRAIAggATYCEAwBCyAIIAE2AhQLIAFFDQELIAEgCDYCGCAFKAIQIgIEQCABIAI2AhAgAiABNgIYCyAFKAIUIgJFDQAgASACNgIUIAIgATYCGAsgAyAAQQFyNgIEIAAgA2ogADYCACADIAdHDQBBrCwgADYCAA8LIABB/wFNBEAgAEF4cUHMLGohAgJ/QaQsKAIAIgRBASAAQQN2dCIAcUUEQEGkLCAAIARyNgIAIAIMAQsgAigCCAshACACIAM2AgggACADNgIMIAMgAjYCDCADIAA2AggPC0EfIQEgAEH///8HTQRAIABBJiAAQQh2ZyICa3ZBAXEgAkEBdGtBPmohAQsgAyABNgIcIANCADcCECABQQJ0QdQuaiEEAn8CQAJ/QagsKAIAIgZBASABdCICcUUEQEGoLCACIAZyNgIAIAQgAzYCAEEYIQFBCAwBCyAAQRkgAUEBdmtBACABQR9HG3QhASAEKAIAIQQDQCAEIgIoAgRBeHEgAEYNAiABQR12IQQgAUEBdCEBIAIgBEEEcWoiBigCECIEDQALIAYgAzYCEEEYIQEgAiEEQQgLIQAgAyICDAELIAIoAggiBCADNgIMIAIgAzYCCEEYIQBBCCEBQQALIQYgASADaiAENgIAIAMgAjYCDCAAIANqIAY2AgBBxCxBxCwoAgBBAWsiAEF/IAAbNgIACwsGACAAJAALBAAjAAsL/BoNAEGACAtNYXVkaW9fb3V0AHVtaS1zeW50aC1wcm9jZXNzb3IAbWlkaV9pbgBVTUkgU3ludGgAVU1JLU9TADEuMC4wAAAAAB4EAAAAAQAAAAQAAAEAQdYIC6EY8D90hRXTsNnvPw+J+WxYte8/UVsS0AGT7z97UX08uHLvP6q5aDGHVO8/OGJ1bno47z/h3h/1nR7vPxW3MQr+Bu8/y6k6N6fx7j8iNBJMpt7uPy2JYWAIzu4/Jyo21dq/7j+CT51WK7TuPylUSN0Hq+4/hVU6sH6k7j/NO39mnqDuP3Rf7Oh1n+4/hwHrcxSh7j8TzkyZiaXuP9ugKkLlrO4/5cXNsDe37j+Q8KOCkcTuP10lPrID1e4/rdNamZ/o7j9HXvvydv/uP5xShd2bGe8/aZDv3CA37z+HpPvcGFjvP1+bezOXfO8/2pCkoq+k7z9ARW5bdtDvPwAAAAAAAOhClCORS/hqrD/zxPpQzr/OP9ZSDP9CLuY/AAAAAAAAOEP+gitlRxVHQJQjkUv4arw+88T6UM6/Lj/WUgz/Qi6WPwAAAAAAAAAAAwAAAAQAAAAEAAAABgAAAIP5ogBETm4A/CkVANFXJwDdNPUAYtvAADyZlQBBkEMAY1H+ALveqwC3YcUAOm4kANJNQgBJBuAACeouAByS0QDrHf4AKbEcAOg+pwD1NYIARLsuAJzphAC0JnAAQX5fANaROQBTgzkAnPQ5AItfhAAo+b0A+B87AN7/lwAPmAUAES/vAApaiwBtH20Az342AAnLJwBGT7cAnmY/AC3qXwC6J3UA5evHAD178QD3OQcAklKKAPtr6gAfsV8ACF2NADADVgB7/EYA8KtrACC8zwA29JoA46kdAF5hkQAIG+YAhZllAKAUXwCNQGgAgNj/ACdzTQAGBjEAylYVAMmocwB74mAAa4zAABnERwDNZ8MACejcAFmDKgCLdsQAphyWAESv3QAZV9EApT4FAAUH/wAzfj8AwjLoAJhP3gC7fTIAJj3DAB5r7wCf+F4ANR86AH/yygDxhx0AfJAhAGokfADVbvoAMC13ABU7QwC1FMYAwxmdAK3EwgAsTUEADABdAIZ9RgDjcS0Am8aaADNiAAC00nwAtKeXADdV1QDXPvYAoxAYAE12/ABknSoAcNerAGN8+AB6sFcAFxXnAMBJVgA71tkAp4Q4ACQjywDWincAWlQjAAAfuQDxChsAGc7fAJ8x/wBmHmoAmVdhAKz7RwB+f9gAImW3ADLoiQDmv2AA78TNAGw2CQBdP9QAFt7XAFg73gDem5IA0iIoACiG6ADiWE0AxsoyAAjjFgDgfcsAF8BQAPMdpwAY4FsALhM0AIMSYgCDSAEA9Y5bAK2wfwAe6fIASEpDABBn0wCq3dgArl9CAGphzgAKKKQA05m0AAam8gBcd38Ao8KDAGE8iACKc3gAr4xaAG/XvQAtpmMA9L/LAI2B7wAmwWcAVcpFAMrZNgAoqNIAwmGNABLJdwAEJhQAEkabAMRZxADIxUQATbKRAAAX8wDUQ60AKUnlAP3VEAAAvvwAHpTMAHDO7gATPvUA7PGAALPnwwDH+CgAkwWUAMFxPgAuCbMAC0XzAIgSnACrIHsALrWfAEeSwgB7Mi8ADFVtAHKnkABr5x8AMcuWAHkWSgBBeeIA9N+JAOiUlwDi5oQAmTGXAIjtawBfXzYAu/0OAEiatABnpGwAcXJCAI1dMgCfFbgAvOUJAI0xJQD3dDkAMAUcAA0MAQBLCGgALO5YAEeqkAB05wIAvdYkAPd9pgBuSHIAnxbvAI6UpgC0kfYA0VNRAM8K8gAgmDMA9Ut+ALJjaADdPl8AQF0DAIWJfwBVUikAN2TAAG3YEAAySDIAW0x1AE5x1ABFVG4ACwnBACr1aQAUZtUAJwedAF0EUAC0O9sA6nbFAIf5FwBJa30AHSe6AJZpKQDGzKwArRRUAJDiagCI2YkALHJQAASkvgB3B5QA8zBwAAD8JwDqcagAZsJJAGTgPQCX3YMAoz+XAEOU/QANhowAMUHeAJI5nQDdcIwAF7fnAAjfOwAVNysAXICgAFqAkwAQEZIAD+jYAGyArwDb/0sAOJAPAFkYdgBipRUAYcu7AMeJuQAQQL0A0vIEAEl1JwDrtvYA2yK7AAoUqgCJJi8AZIN2AAk7MwAOlBoAUTqqAB2jwgCv7a4AXCYSAG3CTQAtepwAwFaXAAM/gwAJ8PYAK0CMAG0xmQA5tAcADCAVANjDWwD1ksQAxq1LAE7KpQCnN80A5qk2AKuSlADdQmgAGWPeAHaM7wBoi1IA/Ns3AK6hqwDfFTEAAK6hAAz72gBkTWYA7QW3ACllMABXVr8AR/86AGr5uQB1vvMAKJPfAKuAMABmjPYABMsVAPoiBgDZ5B0APbOkAFcbjwA2zQkATkLpABO+pAAzI7UA8KoaAE9lqADSwaUACz8PAFt4zQAj+XYAe4sEAIkXcgDGplMAb27iAO/rAACbSlgAxNq3AKpmugB2z88A0QIdALHxLQCMmcEAw613AIZI2gD3XaAAxoD0AKzwLwDd7JoAP1y8ANDebQCQxx8AKtu2AKMlOgAAr5oArVOTALZXBAApLbQAS4B+ANoHpwB2qg4Ae1mhABYSKgDcty0A+uX9AInb/gCJvv0A5HZsAAap/AA+gHAAhW4VAP2H/wAoPgcAYWczACoYhgBNveoAs+evAI9tbgCVZzkAMb9bAITXSAAw3xYAxy1DACVhNQDJcM4AMMu4AL9s/QCkAKIABWzkAFrdoAAhb0cAYhLSALlchABwYUkAa1bgAJlSAQBQVTcAHtW3ADPxxAATbl8AXTDkAIUuqQAdssMAoTI2AAi3pADqsdQAFvchAI9p5AAn/3cADAOAAI1ALQBPzaAAIKWZALOi0wAvXQoAtPlCABHaywB9vtAAm9vBAKsXvQDKooEACGpcAC5VFwAnAFUAfxTwAOEHhgAUC2QAlkGNAIe+3gDa/SoAayW2AHuJNAAF8/4Aub+eAGhqTwBKKqgAT8RaAC34vADXWpgA9MeVAA1NjQAgOqYApFdfABQ/sQCAOJUAzCABAHHdhgDJ3rYAv2D1AE1lEQABB2sAjLCsALLA0ABRVUgAHvsOAJVywwCjBjsAwEA1AAbcewDgRcwATin6ANbKyADo80EAfGTeAJtk2ADZvjEApJfDAHdY1ABp48UA8NoTALo6PABGGEYAVXVfANK99QBuksYArC5dAA5E7QAcPkIAYcSHACn96QDn1vMAInzKAG+RNQAI4MUA/9eNAG5q4gCw/cYAkwjBAHxddABrrbIAzW6dAD5yewDGEWoA98+pAClz3wC1yboAtwBRAOKyDQB0uiQA5X1gAHTYigANFSwAgRgMAH5mlAABKRYAn3p2AP39vgBWRe8A2X42AOzZEwCLurkAxJf8ADGoJwDxbsMAlMU2ANioVgC0qLUAz8wOABKJLQBvVzQALFaJAJnO4wDWILkAa16qAD4qnAARX8wA/QtKAOH0+wCOO20A4oYsAOnUhAD8tKkA7+7RAC41yQAvOWEAOCFEABvZyACB/AoA+0pqAC8c2ABTtIQATpmMAFQizAAqVdwAwMbWAAsZlgAacLgAaZVkACZaYAA/Uu4AfxEPAPS1EQD8y/UANLwtADS87gDoXcwA3V5gAGeOmwCSM+8AyRe4AGFYmwDhV7wAUYPGANg+EADdcUgALRzdAK8YoQAhLEYAWfPXANl6mACeVMAAT4b6AFYG/ADlea4AiSI2ADitIgBnk9wAVeiqAIImOADK55sAUQ2kAJkzsQCp1w4AaQVIAGWy8AB/iKcAiEyXAPnRNgAhkrMAe4JKAJjPIQBAn9wA3EdVAOF0OgBn60IA/p3fAF7UXwB7Z6QAuqx6AFX2ogAriCMAQbpVAFluCAAhKoYAOUeDAInj5gDlntQASftAAP9W6QAcD8oAxVmKAJT6KwDTwcUAD8XPANtargBHxYYAhUNiACGGOwAseZQAEGGHACpMewCALBoAQ78SAIgmkAB4PIkAqMTkAOXbewDEOsIAJvTqAPdnigANkr8AZaMrAD2TsQC9fAsApFHcACfdYwBp4d0AmpQZAKgplQBozigACe20AESfIABOmMoAcIJjAH58IwAPuTIAp/WOABRW5wAh8QgAtZ0qAG9+TQClGVEAtfmrAILf1gCW3WEAFjYCAMQ6nwCDoqEAcu1tADmNegCCuKkAazJcAEYnWwAANO0A0gB3APz0VQABWU0A4HGAAEGDIQs9QPsh+T8AAAAALUR0PgAAAICYRvg8AAAAYFHMeDsAAACAgxvwOQAAAEAgJXo4AAAAgCKC4zYAAAAAHfNpNQBBwSELA4A7RwBBziELAoA/AEHrIQsVP28SAzsK16M8CtcjPQCAO0c+w643AEGWIgsCgD8AQbMiCxU/bxIDOwrXozwK1yM9AIA7Rz7DrjcAQd4iCwKAPwBB+yILFT9vEgM7CtejPArXIz0AgDtHPsOuNwBBpiMLAoA/AEHDIwsVP28SAzsK16M8CtcjPQCAO0c+w643AEHlIwsigDtHAAAgQQAAyEIzMzM/AABIQwAA+kSamZk+AACAPyAYAQ==";

// Decode base64 to ArrayBuffer
function base64ToArrayBuffer(base64) {
    const binaryString = atob(base64);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
    }
    return bytes.buffer;
}

// atob polyfill for AudioWorkletGlobalScope
if (typeof atob === "undefined") {
    var atob = function(base64) {
        const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        let result = "";
        base64 = base64.replace(/=+$/, "");
        for (let i = 0; i < base64.length; i += 4) {
            const a = chars.indexOf(base64[i]);
            const b = chars.indexOf(base64[i + 1]);
            const c = chars.indexOf(base64[i + 2]);
            const d = chars.indexOf(base64[i + 3]);
            result += String.fromCharCode((a << 2) | (b >> 4));
            if (base64[i + 2] !== undefined && base64[i + 2] !== '=')
                result += String.fromCharCode(((b & 15) << 4) | (c >> 2));
            if (base64[i + 3] !== undefined && base64[i + 3] !== '=')
                result += String.fromCharCode(((c & 3) << 6) | d);
        }
        return result;
    };
}

/**
 * UMI Synth AudioWorklet Processor
 */
class UmiSynthProcessor extends AudioWorkletProcessor {
    constructor(options) {
        super();
        this.ready = false;
        this.wasmExports = null;
        this.wasmMemory = null;

        // Fixed buffer addresses in WASM memory
        this.inputPtr = 65536;
        this.outputPtr = 65536 + 128 * 4;

        // Pending note events before WASM is ready
        this.pendingNotes = [];

        // Sample rate from AudioContext
        this.sampleRateValue = options.processorOptions?.sampleRate || sampleRate;

        // Message handler
        this.port.onmessage = (e) => this._handleMessage(e.data);

        // Initialize WASM
        this._initWasm();
    }

    async _initWasm() {
        try {
            // Decode WASM binary from base64
            const wasmBytes = base64ToArrayBuffer(WASM_BASE64);

            // Import object - WASI stubs + env stubs
            // The WASM expects these imports based on its import section
            const importObject = {
                wasi_snapshot_preview1: {
                    args_sizes_get: (argc_ptr, argv_buf_size_ptr) => {
                        // Return 0 args, 0 buffer size
                        return 0;
                    },
                    args_get: (argv_ptr, argv_buf_ptr) => {
                        return 0;
                    },
                    proc_exit: (code) => {
                        // No-op in worklet
                    }
                },
                env: {
                    __main_argc_argv: (argc, argv) => {
                        return 0;
                    }
                }
            };

            // Instantiate WASM
            const result = await WebAssembly.instantiate(wasmBytes, importObject);
            this.wasmExports = result.instance.exports;
            this.wasmMemory = this.wasmExports.memory;

            // Initialize Emscripten runtime - call __wasm_call_ctors if available
            // Do NOT call _start - it causes unreachable trap
            const wasmCallCtors = this.wasmExports.__wasm_call_ctors;
            if (wasmCallCtors) {
                console.log('[UmiSynthProcessor] Calling __wasm_call_ctors...');
                wasmCallCtors();
            }

            // Initialize synth with umi_create
            if (this.wasmExports.umi_create) {
                this.wasmExports.umi_create();
            }

            // Process any pending notes
            for (const note of this.pendingNotes) {
                if (note.on) {
                    this.wasmExports.umi_note_on(note.note, note.velocity);
                } else {
                    this.wasmExports.umi_note_off(note.note);
                }
            }
            this.pendingNotes = [];

            this.ready = true;
            this.port.postMessage({ type: 'ready' });
            console.log('[UmiSynthProcessor] WASM initialized, sample rate:', this.sampleRateValue);

        } catch (err) {
            console.error('[UmiSynthProcessor] WASM init error:', err);
            this.port.postMessage({ type: 'error', message: err.message });
        }
    }

    _handleMessage(msg) {
        switch (msg.type) {
            case 'note-on':
                if (this.ready && this.wasmExports) {
                    this.wasmExports.umi_note_on(msg.note, msg.velocity);
                } else {
                    this.pendingNotes.push({ on: true, note: msg.note, velocity: msg.velocity });
                }
                break;

            case 'note-off':
                if (this.ready && this.wasmExports) {
                    this.wasmExports.umi_note_off(msg.note);
                } else {
                    this.pendingNotes.push({ on: false, note: msg.note });
                }
                break;

            case 'set-param':
                if (this.ready && this.wasmExports) {
                    this.wasmExports.umi_set_param(msg.index, msg.value);
                }
                break;
        }
    }

    process(inputs, outputs, parameters) {
        const output = outputs[0];
        if (!output || output.length === 0) return true;

        const outputChannel = output[0];
        const numFrames = outputChannel.length;

        if (!this.ready || !this.wasmExports) {
            outputChannel.fill(0);
            return true;
        }

        try {
            // Call umi_process with 4 arguments: input, output, frames, sample_rate
            this.wasmExports.umi_process(
                this.inputPtr,
                this.outputPtr,
                numFrames,
                Math.round(this.sampleRateValue)
            );

            // Copy output from WASM memory
            const heap = new Float32Array(this.wasmMemory.buffer);
            const start = this.outputPtr / 4;  // Convert byte offset to float offset
            outputChannel.set(heap.subarray(start, start + numFrames));

            // Copy to all channels
            for (let ch = 1; ch < output.length; ch++) {
                output[ch].set(outputChannel);
            }

        } catch (err) {
            console.error('[UmiSynthProcessor] process error:', err);
            outputChannel.fill(0);
        }

        return true;
    }
}

// Register processor
try {
    registerProcessor('umi-synth-processor', UmiSynthProcessor);
    console.log('[UMI] umi-synth-processor registered');
} catch (err) {
    console.error('[UMI] Failed to register processor:', err);
}
